/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MyThread;
import Controller.Paint_2D;
import static Controller.Paint_2D.drawingLocation;
import Controller.Paint_3D;
import Model.BasicMethod;
import Model.Windmill;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ItemEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRootPane;

/**
 *
 * @author chuon
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public static boolean drawing2D = true;
    private Paint_2D paint2D;
    private Paint_3D paint3D;
    private static int dem = 0;
    private static Boolean draw3D;
    
    public GUI() {
        initComponents();
        this.draw3D = false;
        btn2D.setEnabled(false);
        btnSphere.setEnabled(false);
        btnRectPrism.setEnabled(false);
        btnClear3D.setEnabled(false);
        btnPlay_Stop.setEnabled(false); 
        drawPane.setLayout(new BorderLayout());
        paint2D = new Paint_2D(this, drawPane);
        drawPane.add(paint2D, BorderLayout.CENTER);
        drawPane.repaint();
        btnPlay_Stop.setSelected(true);
        validate();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfoSphere = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();
        drawPane = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn2D = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn3D = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnPlay_Stop = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnSphere = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnRectPrism = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnClear3D = new javax.swing.JButton();
        panelMainInfo = new javax.swing.JPanel();
        panelInfo2D = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWindMillA = new javax.swing.JLabel();
        lblWindMillB = new javax.swing.JLabel();
        lblWindMillC = new javax.swing.JLabel();
        lblWindMillD = new javax.swing.JLabel();
        lblWindMillA2 = new javax.swing.JLabel();
        lblWindMillB2 = new javax.swing.JLabel();
        lblWindMillC2 = new javax.swing.JLabel();
        lblWindMillD2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBlade1A = new javax.swing.JLabel();
        lblBlade1B = new javax.swing.JLabel();
        lblBlade1C = new javax.swing.JLabel();
        lblRadius = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCloudLeft = new javax.swing.JLabel();
        lblCloudCenter = new javax.swing.JLabel();
        lblCloudRight = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSun = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblBlade1A2 = new javax.swing.JLabel();
        lblBlade1B2 = new javax.swing.JLabel();
        lblBlade1C2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblWindowA = new javax.swing.JLabel();
        lblWindowB = new javax.swing.JLabel();
        lblWindowC = new javax.swing.JLabel();
        lblWindowD = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblLeftMirrorA = new javax.swing.JLabel();
        lblLeftMirrorB = new javax.swing.JLabel();
        lblLeftMirrorC = new javax.swing.JLabel();
        lblLeftMirrorD = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblRearC = new javax.swing.JLabel();
        lblRearD = new javax.swing.JLabel();
        lblRearA = new javax.swing.JLabel();
        lblRearB = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblRightMirrorA = new javax.swing.JLabel();
        lblRightMirrorB = new javax.swing.JLabel();
        lblRightMirrorC = new javax.swing.JLabel();
        lblRightMirrorD = new javax.swing.JLabel();

        jLabel4.setText("Thông Số Hình Cầu");

        javax.swing.GroupLayout panelInfoSphereLayout = new javax.swing.GroupLayout(panelInfoSphere);
        panelInfoSphere.setLayout(panelInfoSphereLayout);
        panelInfoSphereLayout.setHorizontalGroup(
            panelInfoSphereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoSphereLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInfoSphereLayout.setVerticalGroup(
            panelInfoSphereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoSphereLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        contentPane.setLayout(new java.awt.BorderLayout());

        drawPane.setBackground(new java.awt.Color(204, 204, 255));
        drawPane.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout drawPaneLayout = new javax.swing.GroupLayout(drawPane);
        drawPane.setLayout(drawPaneLayout);
        drawPaneLayout.setHorizontalGroup(
            drawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        drawPaneLayout.setVerticalGroup(
            drawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        contentPane.add(drawPane, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnExit.setText("EXIT");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(jSeparator1);

        btn2D.setText("2D");
        btn2D.setFocusable(false);
        btn2D.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2D.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DActionPerformed(evt);
            }
        });
        jToolBar1.add(btn2D);
        jToolBar1.add(jSeparator2);

        btn3D.setText("3D");
        btn3D.setFocusable(false);
        btn3D.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3D.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3DActionPerformed(evt);
            }
        });
        jToolBar1.add(btn3D);
        jToolBar1.add(jSeparator3);

        btnPlay_Stop.setText("PLAY/STOP");
        btnPlay_Stop.setFocusable(false);
        btnPlay_Stop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlay_Stop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlay_Stop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnPlay_StopItemStateChanged(evt);
            }
        });
        jToolBar1.add(btnPlay_Stop);
        jToolBar1.add(jSeparator4);

        btnSphere.setText("SPHERE");
        btnSphere.setFocusable(false);
        btnSphere.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSphere.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSphereActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSphere);
        jToolBar1.add(jSeparator5);

        btnRectPrism.setText("RECTANGLE PRISM");
        btnRectPrism.setFocusable(false);
        btnRectPrism.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRectPrism.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRectPrism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectPrismActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRectPrism);
        jToolBar1.add(jSeparator6);

        btnClear3D.setText("CLEAR 3D");
        btnClear3D.setFocusable(false);
        btnClear3D.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear3D.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClear3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3DActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClear3D);

        contentPane.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        panelInfo2D.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(204, 0, 255)));
        panelInfo2D.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Thông Số:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new Color(0, 102, 204));
        jLabel2.setText("Trụ Cối Xoay Gió Gốc");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Trụ Cối Xoay Gió Đối Xứng");

        lblWindMillA.setText("A()");

        lblWindMillB.setText("B()");

        lblWindMillC.setText("C()");

        lblWindMillD.setText("D()");

        lblWindMillA2.setText("A()");

        lblWindMillB2.setText("B()");

        lblWindMillC2.setText("C()");

        lblWindMillD2.setText("D()");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel12.setForeground(Color.RED);
        jLabel12.setText("Bán Kính Cối Xoay Gió Gốc");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setForeground(Color.RED);
        jLabel13.setText("Tọa Độ Cánh Quạt 1 Gốc");

        lblBlade1A.setText("A()");

        lblBlade1B.setText("B()");

        lblBlade1C.setText("C()");

        lblRadius.setText("R = ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tọa Độ Tâm 3 Hình Tròn Đám Mây");

        lblCloudLeft.setText("OLeft()");

        lblCloudCenter.setText("OCenter()");

        lblCloudRight.setText("ORight()");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setForeground(Color.RED);
        jLabel9.setText("Tọa Độ Tâm Mặt Trời");

        lblSun.setText("O()");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("Tọa Độ Cánh Quạt 1 Đối Xứng");

        lblBlade1A2.setText("A()");

        lblBlade1B2.setText("B()");

        lblBlade1C2.setText("C()");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setText("Tọa Độ Xe");

        jLabel15.setText("Kính Sau");

        lblWindowA.setText("A()");

        lblWindowB.setText("B()");

        lblWindowC.setText("C()");

        lblWindowD.setText("D()");

        jLabel16.setText("Gương Trái");

        lblLeftMirrorA.setText("A()");

        lblLeftMirrorB.setText("B()");

        lblLeftMirrorC.setText("C()");

        lblLeftMirrorD.setText("D()");

        jLabel17.setText("Gương Phải");

        lblRearC.setText("C()");

        lblRearD.setText("D()");

        lblRearA.setText("A()");

        lblRearB.setText("B()");

        jLabel18.setText("Cốp Xe");

        lblRightMirrorA.setText("A()");

        lblRightMirrorB.setText("B()");

        lblRightMirrorC.setText("C()");

        lblRightMirrorD.setText("D()");

        javax.swing.GroupLayout panelInfo2DLayout = new javax.swing.GroupLayout(panelInfo2D);
        panelInfo2D.setLayout(panelInfo2DLayout);
        panelInfo2DLayout.setHorizontalGroup(
            panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfo2DLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addComponent(lblWindMillA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblWindMillB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addComponent(lblWindMillC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblWindMillD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                .addComponent(lblWindMillA2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblWindMillB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                .addComponent(lblWindMillD2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblWindMillC2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblSun, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                .addComponent(lblBlade1A, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblBlade1B, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblBlade1C, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                .addComponent(lblBlade1A2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblBlade1B2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBlade1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInfo2DLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblLeftMirrorC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblLeftMirrorD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblLeftMirrorA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblLeftMirrorB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblWindowC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblWindowD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblWindowA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblWindowB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblRearC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRearD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblRearA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblRearB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblRightMirrorC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblRightMirrorD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelInfo2DLayout.createSequentialGroup()
                                                    .addComponent(lblRightMirrorA, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblRightMirrorB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                                        .addComponent(lblCloudLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCloudCenter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCloudRight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBlade1A, lblBlade1B, lblBlade1C, lblWindMillA, lblWindMillA2, lblWindMillB, lblWindMillB2, lblWindMillC, lblWindMillC2, lblWindMillD, lblWindMillD2});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCloudCenter, lblCloudLeft, lblCloudRight, lblRadius, lblSun});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBlade1A2, lblBlade1B2, lblBlade1C2});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblWindowA, lblWindowB});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLeftMirrorA, lblLeftMirrorB, lblLeftMirrorC, lblLeftMirrorD, lblWindowC, lblWindowD});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRearA, lblRearB, lblRearC});

        panelInfo2DLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRightMirrorA, lblRightMirrorB, lblRightMirrorC, lblRightMirrorD});

        panelInfo2DLayout.setVerticalGroup(
            panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfo2DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWindMillA)
                            .addComponent(lblWindMillB))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWindMillC)
                            .addComponent(lblWindMillD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWindMillA2)
                            .addComponent(lblWindMillB2))
                        .addGap(11, 11, 11)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWindMillD2)
                            .addComponent(lblWindMillC2))))
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlade1A)
                    .addComponent(lblBlade1B)
                    .addComponent(lblBlade1C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlade1A2)
                    .addComponent(lblBlade1B2)
                    .addComponent(lblBlade1C2))
                .addGap(18, 18, 18)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblRadius))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCloudLeft)
                    .addComponent(lblCloudCenter)
                    .addComponent(lblCloudRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblSun))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblWindowA)
                    .addComponent(lblWindowB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWindowC)
                    .addComponent(lblWindowD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLeftMirrorA)
                            .addComponent(lblLeftMirrorB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLeftMirrorC)
                            .addComponent(lblLeftMirrorD))))
                .addGap(7, 7, 7)
                .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(36, 36, 36)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRearA)
                            .addComponent(lblRearB)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRearC)
                            .addComponent(lblRearD)))
                    .addGroup(panelInfo2DLayout.createSequentialGroup()
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRightMirrorA)
                            .addComponent(lblRightMirrorB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRightMirrorC)
                            .addComponent(lblRightMirrorD))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainInfoLayout = new javax.swing.GroupLayout(panelMainInfo);
        panelMainInfo.setLayout(panelMainInfoLayout);
        panelMainInfoLayout.setHorizontalGroup(
            panelMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainInfoLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(panelInfo2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMainInfoLayout.setVerticalGroup(
            panelMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMainInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelMainInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlay_StopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnPlay_StopItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //System.out.println("Dang bat len");
            drawing2D = true;
            new MyThread(paint2D).start();
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            drawing2D = false;
        }
    }//GEN-LAST:event_btnPlay_StopItemStateChanged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        drawing2D = false;
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DActionPerformed
        // ko con trang thai ve 3D nua
        this.draw3D = false;
        drawing2D = true;
        // thiet lap cac nut co the truy cap
        btn3D.setEnabled(true);
        btn2D.setEnabled(false);
        //btnPlay_Stop.setEnabled(true);
                btnSphere.setEnabled(false);
        btnRectPrism.setEnabled(false);
        btnClear3D.setEnabled(false);
        // reset drawPane
        drawPane.removeAll();
        paint2D = new Paint_2D(this, drawPane);
        drawPane.add(paint2D);
        drawPane.validate();
        // chay animation
        btnPlay_Stop.setSelected(true);
        panelInfo2D.setVisible(true);
    }//GEN-LAST:event_btn2DActionPerformed

    private void btn3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3DActionPerformed
        // ko con trang thai ve 2D nua
        this.drawing2D = false;
        this.draw3D = true;
        // thiet lap cac nut co the truy cap
        btn2D.setEnabled(true);
        btn3D.setEnabled(false);
        //btnPlay_Stop.setEnabled(false);
        btnSphere.setEnabled(true);
        btnRectPrism.setEnabled(true);
        btnClear3D.setEnabled(true);
        // reset drawPane
        drawPane.removeAll();
        paint3D = new Paint_3D(drawPane);
        drawPane.add(paint3D);
        drawPane.repaint();
        drawPane.validate();
        // chay animation, render Draw Paint
        btnPlay_Stop.setSelected(false);
        panelInfo2D.setVisible(false);
    }//GEN-LAST:event_btn3DActionPerformed

    private void btnSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSphereActionPerformed
       SphereInputDialog dlg =  new SphereInputDialog(this, true);
       dlg.setVisible(true);
       if(dlg.getSphere()!= null){
           Paint_3D.sphere = dlg.getSphere();
           paint3D.repaint();
       }
       dlg.dispose();
    }//GEN-LAST:event_btnSphereActionPerformed

    private void btnRectPrismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectPrismActionPerformed
        RectPrismDlg dlg = new RectPrismDlg(this, true);
        dlg.setVisible(true);
        if (dlg.getRectPrism() != null) {
            Paint_3D.rectPrism = dlg.getRectPrism();
            paint3D.repaint();
        }
       dlg.dispose();
    }//GEN-LAST:event_btnRectPrismActionPerformed

    private void btnClear3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3DActionPerformed
        Paint_3D.list3DObject.clear();
        paint3D.repaint();
    }//GEN-LAST:event_btnClear3DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI frame = new GUI();
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
                frame.validate();
//        Dimension frameSize = frame.getContentPane().getSize();
//        Insets insets = frame.getInsets();
//        System.out.println("frame.getSize()= " + frameSize);
//        System.out.println("Insets" + insets);
//        double realWidth = frameSize.getWidth() - (insets.left + insets.right);
//        double realHeight = frameSize.getHeight() - (insets.top + insets.bottom);
//        System.out.println("frame real width= "+ realWidth + " real Height= " + realHeight);
            }
        });
    }

    public JLabel getLblBlade1A() {
        return lblBlade1A;
    }

    public JLabel getLblBlade1B() {
        return lblBlade1B;
    }

    public JLabel getLblBlade1C() {
        return lblBlade1C;
    }

    public JLabel getLblRadius() {
        return lblRadius;
    }

    public JLabel getLblWindMillA() {
        return lblWindMillA;
    }

    public JLabel getLblWindMillA2() {
        return lblWindMillA2;
    }

    public JLabel getLblWindMillB() {
        return lblWindMillB;
    }

    public JLabel getLblWindMillB2() {
        return lblWindMillB2;
    }

    public JLabel getLblWindMillC() {
        return lblWindMillC;
    }

    public JLabel getLblWindMillC2() {
        return lblWindMillC2;
    }

    public JLabel getLblWindMillD() {
        return lblWindMillD;
    }

    public JLabel getLblWindMillD2() {
        return lblWindMillD2;
    }
    
    public JLabel getLblBlade1A2() {
        return lblBlade1A2;
    }

    public JLabel getLblBlade1B2() {
        return lblBlade1B2;
    }

    public JLabel getLblBlade1C2() {
        return lblBlade1C2;
    }

    public JLabel getLblCloudCenter() {
        return lblCloudCenter;
    }

    public JLabel getLblCloudLeft() {
        return lblCloudLeft;
    }

    public JLabel getLblCloudRight() {
        return lblCloudRight;
    }

    public JLabel getLblLeftMirrorA() {
        return lblLeftMirrorA;
    }

    public JLabel getLblLeftMirrorB() {
        return lblLeftMirrorB;
    }

    public JLabel getLblLeftMirrorC() {
        return lblLeftMirrorC;
    }

    public JLabel getLblLeftMirrorD() {
        return lblLeftMirrorD;
    }

    public JLabel getLblSun() {
        return lblSun;
    }

    public JLabel getLblWindowA() {
        return lblWindowA;
    }

    public JLabel getLblWindowB() {
        return lblWindowB;
    }

    public JLabel getLblWindowC() {
        return lblWindowC;
    }

    public JLabel getLblWindowD() {
        return lblWindowD;
    }

    public JLabel getLblRightMirrorA() {
        return lblRightMirrorA;
    }

    public JLabel getLblRightMirrorB() {
        return lblRightMirrorB;
    }

    public JLabel getLblRightMirrorC() {
        return lblRightMirrorC;
    }

    public JLabel getLblRightMirrorD() {
        return lblRightMirrorD;
    }

    public JLabel getLblRearA() {
        return lblRearA;
    }

    public JLabel getLblRearB() {
        return lblRearB;
    }

    public JLabel getLblRearC() {
        return lblRearC;
    }

    public JLabel getLblRearD() {
        return lblRearD;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2D;
    private javax.swing.JButton btn3D;
    private javax.swing.JButton btnClear3D;
    private javax.swing.JButton btnExit;
    private javax.swing.JToggleButton btnPlay_Stop;
    private javax.swing.JButton btnRectPrism;
    private javax.swing.JButton btnSphere;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel drawPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBlade1A;
    private javax.swing.JLabel lblBlade1A2;
    private javax.swing.JLabel lblBlade1B;
    private javax.swing.JLabel lblBlade1B2;
    private javax.swing.JLabel lblBlade1C;
    private javax.swing.JLabel lblBlade1C2;
    private javax.swing.JLabel lblCloudCenter;
    private javax.swing.JLabel lblCloudLeft;
    private javax.swing.JLabel lblCloudRight;
    private javax.swing.JLabel lblLeftMirrorA;
    private javax.swing.JLabel lblLeftMirrorB;
    private javax.swing.JLabel lblLeftMirrorC;
    private javax.swing.JLabel lblLeftMirrorD;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JLabel lblRearA;
    private javax.swing.JLabel lblRearB;
    private javax.swing.JLabel lblRearC;
    private javax.swing.JLabel lblRearD;
    private javax.swing.JLabel lblRightMirrorA;
    private javax.swing.JLabel lblRightMirrorB;
    private javax.swing.JLabel lblRightMirrorC;
    private javax.swing.JLabel lblRightMirrorD;
    private javax.swing.JLabel lblSun;
    private javax.swing.JLabel lblWindMillA;
    private javax.swing.JLabel lblWindMillA2;
    private javax.swing.JLabel lblWindMillB;
    private javax.swing.JLabel lblWindMillB2;
    private javax.swing.JLabel lblWindMillC;
    private javax.swing.JLabel lblWindMillC2;
    private javax.swing.JLabel lblWindMillD;
    private javax.swing.JLabel lblWindMillD2;
    private javax.swing.JLabel lblWindowA;
    private javax.swing.JLabel lblWindowB;
    private javax.swing.JLabel lblWindowC;
    private javax.swing.JLabel lblWindowD;
    private javax.swing.JPanel panelInfo2D;
    private javax.swing.JPanel panelInfoSphere;
    private javax.swing.JPanel panelMainInfo;
    // End of variables declaration//GEN-END:variables
}
